
sudo: required
language: bash

services:
  - docker
  
before_install:
- docker build -t camicroscope_viewer . 
- docker run -itd -v $(pwd)/html:/var/www/html -p 3000:80 camicroscope_viewer
script:
- docker ps | grep -q viewer
